import os



INFLUXDB_PORT_8086_TCP_ADDR=os.getenv('INFLUXDB_PORT_8086_TCP_ADDR')
INFLUXDB_PORT_8086_TCP_PORT=os.getenv('INFLUXDB_PORT_8086_TCP_PORT')
INFLUXDB_USERNAME=os.getenv('INFLUXDB_USERNAME')
INFLUXDB_PASSWORD=os.getenv('INFLUXDB_PASSWORD')


